apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    steps:
      - name: checkout Source Code
        uses: cloudbees-io/checkout@v1

      - id: gitleaks-step
        name: gitleaks hybrid plugin scan
        uses: cloudbees-io/gitleaks-plugin@v1

      
